services:
  altur-anti-spoof:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altur-anti-spoof-platform
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ENV=production
      - DECISION_THRESHOLD=0.50
    restart: unless-stopped
